### PR TITLE
add rootpath to client for additional flexibility

### PR DESCRIPTION
**Pull request by dmorgantini**
Hi Clifton,

We need this to allow the client to be used to contact the seguir-express-middleware.

Thanks!

### CODE REVIEW

**Comment by cliftonc** [comment]
The client shouldn't talk to the middleware - as it talks via a seguir appid and apptoken - this can't be used client side.

The purpose of the middleware was to enable you to quickly tie up our own auth (e.g. TESCookie) and convert that to the call made via the seguir client to seguir.

We actually need to build a client for the middleware that talks the 'TES' style of authentication.  Not sure if this can be the same thing ... need to give it some thought.

**Comment by cliftonc** [comment]
This does look like a good PR, as it adds flexibility to the client and means you can mount seguir wherever you like (from a server API perspective), but I think we need to be careful about our definition of 'client'.

Seguir API <--> Seguir Client <--> Seguir Middleware (Helper) <--> Your App Client **

**Comment by dmorgantini** [comment]
I guess the question is whether or not this can function isomorphically.  If so I don't see how it's much different aside from passing domain cookies along with the request vs passing appid/appsecret.

**Comment by cliftonc** [comment]
It can't at the moment, as it uses restify, so browserify will pull in all of its deps - it would be massive.  I would need to re-write the client so it has no dependencies that can't be used on the browser, plus make the header / auth piece configurable so it doesn't try to send the appid / appsecret in the browser. 

Not saying its a bad idea, but it may just be simpler for now to write a new browser only client for the api defined in seguir-express-middleware - e.g. here is the client for the endpoints defined in this project, and then figure out how if appropriate to merge that into the main seguir client at a later point?

The other challenge (in addition to the auth pieces mentioned above) is that the current seguir client lets you impersonate anyone by providing their specific user ID as the first parameter - it really can't be used anywhere outside of a trusted environment.   This is important - as it lets us systematically add stuff to users feeds, or have it be used in a mobile app back end etc. etc.

**Pull request merged**
