### PR TITLE
Constant user id

### PR DESCRIPTION
**Pull request by dmorgantini**
We would like a mechanism to define a specific user id when creating a user.  This will solve several issues that we have around caching of user ids and clearing the cassandra db.

This will require a SemVar bump, but we would be happy(ish) to make the client backwards compatible.

### CODE REVIEW

**Comment by cliftonc** [comment]
Happy if it is a semver bump.

**Comment by dmorgantini** [comment]
The tests are failing randomly :-(

**Comment by cliftonc** [comment]
It's the cassandra driver - waiting for them to pull and release.

**Comment by dmorgantini** [comment]
Ok, I'm going to Merge with caution!

**Pull request merged**
